on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: bash ./update.sh
